#ifndef SWUPDATEEVENTCODES_H
#define SWUPDATEEVENTCODES_H

#include <../Include/PlatformEventCodes.h>

namespace SWUpdate {
const quint32 EVENT_GROUP_PLATFORM_SW_UPDATE = EVENT_SWU_COPY_FILE_FAILED;
//const quint32 EVENT_SW_UPDATE_FAILED_DUE_TO_TIMEOUT = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0001;
//const quint32 EVENT_SW_UPDATE_EXITED_WITH_ERROR     = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0002;
//const quint32 EVENT_SW_UPDATE_FAILED                = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0003;
//const quint32 EVENT_SW_UPDATE_CHECK_STARTED         = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0004;
//const quint32 EVENT_SW_UPDATE_CHECK_SUCCESSFUL      = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0005;
//const quint32 EVENT_SW_UPDATE_ROLLBACK_FAILED       = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0006;
//const quint32 EVENT_SW_UPDATE_SUCCESS               = EVENT_GROUP_PLATFORM_SW_UPDATE + 0x0007;

}//End of namespace SWUpdate
#endif // SWUPDATEEVENTCODES_H
