// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#ifndef LIBRARY_SSKEL_HXX
#define LIBRARY_SSKEL_HXX

#include <xsde/cxx/version.hxx>

#if (XSDE_INT_VERSION != 3020000L)
#error XSD/e runtime version mismatch
#endif

#include <xsde/cxx/config.hxx>

#ifndef XSDE_ENCODING_UTF8
#error the generated code uses the UTF-8 encodingwhile the XSD/e runtime does not (reconfigure the runtime or change the --char-encoding value)
#endif

#ifndef XSDE_STL
#error the generated code uses STL while the XSD/e runtime does not (reconfigure the runtime or add --no-stl)
#endif

#ifndef XSDE_IOSTREAM
#error the generated code uses iostream while the XSD/e runtime does not (reconfigure the runtime or add --no-iostream)
#endif

#ifndef XSDE_EXCEPTIONS
#error the generated code uses exceptions while the XSD/e runtime does not (reconfigure the runtime or add --no-exceptions)
#endif

#ifndef XSDE_LONGLONG
#error the generated code uses long long while the XSD/e runtime does not (reconfigure the runtime or add --no-long-long)
#endif

#ifndef XSDE_SERIALIZER_VALIDATION
#error the generated code uses validation while the XSD/e runtime does not (reconfigure the runtime or add --suppress-validation)
#endif

#ifdef XSDE_POLYMORPHIC
#error the generated code expects XSD/e runtime without polymorphism support (reconfigure the runtime or add --generate-polymorphic/--runtime-polymorphic)
#endif

#ifndef XSDE_REUSE_STYLE_TIEIN
#error the generated code uses the tiein reuse style while the XSD/e runtime does not (reconfigure the runtime or add --reuse-style-mixin or --reuse-style-none)
#endif

#ifdef XSDE_CUSTOM_ALLOCATOR
#error the XSD/e runtime uses custom allocator while the generated code does not (reconfigure the runtime or add --custom-allocator)
#endif

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//

#include <xsde/cxx/hybrid/any-type.hxx>
#include <xsde/cxx/hybrid/any-type-sskel.hxx>
#include <xsde/cxx/hybrid/any-type-simpl.hxx>

namespace xml_schema
{
  using ::xsde::cxx::hybrid::any_type;

  using ::xsde::cxx::hybrid::any_type_sskel;
  using ::xsde::cxx::hybrid::any_type_simpl;
}


//
// End prologue.

// Forward declarations
//
namespace library
{
  class isbn_sskel;
  class title_sskel;
  class genre_sskel;
  class author_sskel;
  class book_sskel;
  class catalog_sskel;
}


#include "xml-schema-sskel.hxx"

#include "library.hxx"

namespace library
{
  class isbn_sskel: public ::xml_schema::unsigned_int_sskel
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::library::isbn&) = 0;

    // virtual void
    // post ();

    // Constructor.
    //
    isbn_sskel (::xml_schema::unsigned_int_sskel* tiein);

    // Implementation.
    //
    public:
    virtual void
    pre (unsigned int);

    protected:
    isbn_sskel* isbn_impl_;
    isbn_sskel (isbn_sskel*, void*);
  };

  class title_sskel: public ::xml_schema::string_sskel
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::library::title&) = 0;

    // Attributes.
    //
    virtual bool
    lang_present ();

    virtual ::std::string
    lang () = 0;

    // virtual void
    // post ();

    // Serializer construction API.
    //
    void
    serializers (::xml_schema::string_sskel& /* lang */);

    // Individual attribute serializers.
    //
    void
    lang_serializer (::xml_schema::string_sskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    title_sskel (::xml_schema::string_sskel* tiein);

    // Implementation.
    //
    public:
    virtual void
    pre (const ::std::string&);

    virtual void
    _serialize_attributes ();

    protected:
    title_sskel* title_impl_;
    title_sskel (title_sskel*, void*);

    protected:
    ::xml_schema::string_sskel* lang_serializer_;
  };

  class genre_sskel: public ::xml_schema::string_sskel
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::library::genre&) = 0;

    // virtual void
    // post ();

    // Constructor.
    //
    genre_sskel (::xml_schema::string_sskel* tiein);

    // Implementation details.
    //
    virtual void
    pre (const ::std::string&);

    protected:
    genre_sskel* genre_impl_;
    genre_sskel (genre_sskel*, void*);

    protected:
    static const char* const _xsde_genre_sskel_enums_[5UL];
  };

  class author_sskel: public ::xsde::cxx::serializer::validating::complex_content
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::library::author&) = 0;

    // Elements.
    //
    virtual ::std::string
    name () = 0;

    virtual ::xml_schema::date
    born () = 0;

    virtual bool
    died_present ();

    virtual ::xml_schema::date
    died () = 0;

    // virtual void
    // post ();

    // Serializer construction API.
    //
    void
    serializers (::xml_schema::string_sskel& /* name */,
                 ::xml_schema::date_sskel& /* born */,
                 ::xml_schema::date_sskel& /* died */);

    // Individual element serializers.
    //
    void
    name_serializer (::xml_schema::string_sskel&);

    void
    born_serializer (::xml_schema::date_sskel&);

    void
    died_serializer (::xml_schema::date_sskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    author_sskel ();

    // Implementation.
    //
    public:
    virtual void
    _serialize_content ();

    protected:
    author_sskel* author_impl_;
    author_sskel (author_sskel*, void*);

    protected:
    ::xml_schema::string_sskel* name_serializer_;
    ::xml_schema::date_sskel* born_serializer_;
    ::xml_schema::date_sskel* died_serializer_;
  };

  class book_sskel: public ::xsde::cxx::serializer::validating::complex_content
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::library::book&) = 0;

    // Attributes.
    //
    virtual bool
    available_present ();

    virtual bool
    available () = 0;

    // Elements.
    //
    virtual const ::library::isbn&
    isbn () = 0;

    virtual const ::library::title&
    title () = 0;

    virtual const ::library::genre&
    genre () = 0;

    virtual bool
    author_next () = 0;

    virtual const ::library::author&
    author () = 0;

    // virtual void
    // post ();

    // Serializer construction API.
    //
    void
    serializers (::xml_schema::boolean_sskel& /* available */,
                 ::library::isbn_sskel& /* isbn */,
                 ::library::title_sskel& /* title */,
                 ::library::genre_sskel& /* genre */,
                 ::library::author_sskel& /* author */);

    // Individual attribute serializers.
    //
    void
    available_serializer (::xml_schema::boolean_sskel&);

    // Individual element serializers.
    //
    void
    isbn_serializer (::library::isbn_sskel&);

    void
    title_serializer (::library::title_sskel&);

    void
    genre_serializer (::library::genre_sskel&);

    void
    author_serializer (::library::author_sskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    book_sskel ();

    // Implementation.
    //
    public:
    virtual void
    _serialize_attributes ();

    virtual void
    _serialize_content ();

    protected:
    book_sskel* book_impl_;
    book_sskel (book_sskel*, void*);

    protected:
    ::xml_schema::boolean_sskel* available_serializer_;
    ::library::isbn_sskel* isbn_serializer_;
    ::library::title_sskel* title_serializer_;
    ::library::genre_sskel* genre_serializer_;
    ::library::author_sskel* author_serializer_;
  };

  class catalog_sskel: public ::xsde::cxx::serializer::validating::complex_content
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::library::catalog&) = 0;

    // Elements.
    //
    virtual bool
    book_next () = 0;

    virtual const ::library::book&
    book () = 0;

    // virtual void
    // post ();

    // Serializer construction API.
    //
    void
    serializers (::library::book_sskel& /* book */);

    // Individual element serializers.
    //
    void
    book_serializer (::library::book_sskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    catalog_sskel ();

    // Implementation.
    //
    public:
    virtual void
    _serialize_content ();

    protected:
    catalog_sskel* catalog_impl_;
    catalog_sskel (catalog_sskel*, void*);

    protected:
    ::library::book_sskel* book_serializer_;
  };
}

#include "library-sskel.ixx"

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // LIBRARY_SSKEL_HXX
