// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

// Begin prologue.
//
//
// End prologue.

#include "position-simpl.hxx"

#include <xsde/cxx/serializer/validating/string-common.hxx>

// position_simpl
//

void position_simpl::
pre (const ::position& x)
{
  this->position_simpl_state_.position_ = &x;
}

float position_simpl::
lat ()
{
  return this->position_simpl_state_.position_->lat ();
}

float position_simpl::
lon ()
{
  return this->position_simpl_state_.position_->lon ();
}

// object_saggr
//

object_saggr::
object_saggr ()
{
  this->object_s_.serializers (this->unsigned_int_s_,
                               this->position_s_);

  this->position_s_.serializers (this->float_s_,
                                 this->float_s_);
}

const char* object_saggr::
root_name ()
{
  return "object";
}

const char* object_saggr::
root_namespace ()
{
  return "";
}

// Begin epilogue.
//
//
// End epilogue.

