// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

// Begin prologue.
//
//
// End prologue.

#include "position-pimpl.hxx"

#include <xsde/cxx/parser/validating/string-common.hxx>

// position_pimpl
//

void position_pimpl::
pre ()
{
  this->position_pimpl_state_.position_ = ::position ();
}

void position_pimpl::
lat (float x)
{
  this->position_pimpl_state_.position_.lat (x);
}

void position_pimpl::
lon (float x)
{
  this->position_pimpl_state_.position_.lon (x);
}

::position position_pimpl::
post_position ()
{
  return this->position_pimpl_state_.position_;
}

// object_paggr
//

object_paggr::
object_paggr ()
{
  this->object_p_.parsers (this->unsigned_int_p_,
                           this->position_p_);

  this->position_p_.parsers (this->float_p_,
                             this->float_p_);
}

const char* object_paggr::
root_name ()
{
  return "object";
}

const char* object_paggr::
root_namespace ()
{
  return "";
}

// Begin epilogue.
//
//
// End epilogue.

